import type { ImmobileEntity } from "../models/immobile";
import type { UserEntity } from "../models/user";

export const usersList: UserEntity[] = Array.from({ length: 25 }, (_, i) => {
    const id = (i + 1).toString();
    const isEven = i % 2 === 0;
    return {
        id,
        userName: `testUser${id}`,
        userEmail: `test@user${id}.com`,
        phone: '48999999999',
        civilState: 'CASADO',
        bornDate: new Date(2005, 7, 8),
        CreatedAt: new Date(),
        userRole: isEven ? 'ADMIN' : 'OPERATOR',
    };
});

export const exampleImmobile: ImmobileEntity[] = [
    {
        id: "c149f257-7e18-4cf2-b6cd-9814aef311b3",
        localityInfo: "Rua das Palmeiras, 125\nCentro\n12345-678 Silva / SP",
        immobileType: "HABITATION",
        localLink: "https://exemplo.com/imovel1",
        status: "ACTIVE",
        userCreationId: "f8f0344d-324b-4c1c-9158-5a91c1a1c2d3",
        creationDate: new Date("2024-06-01T10:00:00Z"),
        updateDate: new Date("2025-06-01T10:00:00Z"),
        postalCode: "12345-678",
        state: "SP",
        city: "São Paulo",
        street: "Rua das Palmeiras",
        neighborhood: "Centro",
        hasScripture: true,
        immobileDescription: "Casa aconchegante com quintal amplo.",
        value: 250000,
        Images: [
            {
                id: "img-1a",
                type: "image/jpeg",
                imageUrl: "https://picsum.photos/300/200?random=1",
                size: 150000,
                name: "fachada.jpg",
                immobileId: "c149f257-7e18-4cf2-b6cd-9814aef311b3",
                cloudnaryPublicId: ""
            },
            {
                id: "img-1b",
                type: "image/jpeg",
                imageUrl: "https://picsum.photos/300/200?random=2",
                size: 180000,
                name: "sala.jpg",
                immobileId: "c149f257-7e18-4cf2-b6cd-9814aef311b3",
                cloudnaryPublicId: ""
            },
            {
                id: "img-1c",
                type: "image/jpeg",
                imageUrl: "https://picsum.photos/300/200?random=3",
                size: 160000,
                name: "quarto.jpg",
                immobileId: "c149f257-7e18-4cf2-b6cd-9814aef311b3",
                cloudnaryPublicId: ""
            }
        ]
    },

    {
        id: "56781b5e-4048-40b6-a939-0f56b93d9ead",
        localityInfo: "Av. Brasil, 1000\nJardim América\n87654-321 Souza / RJ",
        immobileType: "HABITATION",
        localLink: "https://exemplo.com/imovel2",
        status: "INACTIVE",
        userCreationId: "1228fe45-fe16-45cf-a759-3748c19f7f7e",
        creationDate: new Date("2024-01-15T08:30:00Z"),
        updateDate: new Date("2025-03-22T14:45:00Z"),
        postalCode: "87654-321",
        state: "RJ",
        city: "Rio de Janeiro",
        street: "Av. Brasil",
        neighborhood: "Jardim América",
        hasScripture: true,
        immobileDescription: "Apartamento com vista para o mar e varanda gourmet.",
        value: 480000,
        Images: [
            {
                id: "img-2a",
                type: "image/jpeg",
                imageUrl: "https://picsum.photos/300/200?random=4",
                size: 200000,
                name: "vista.jpg",
                immobileId: "56781b5e-4048-40b6-a939-0f56b93d9ead",
                cloudnaryPublicId: ""
            },
            {
                id: "img-2b",
                type: "image/jpeg",
                imageUrl: "https://picsum.photos/300/200?random=5",
                size: 170000,
                name: "cozinha.jpg",
                immobileId: "56781b5e-4048-40b6-a939-0f56b93d9ead",
                cloudnaryPublicId: ""
            },
            {
                id: "img-2c",
                type: "image/jpeg",
                imageUrl: "https://picsum.photos/300/200?random=6",
                size: 190000,
                name: "banheiro.jpg",
                immobileId: "56781b5e-4048-40b6-a939-0f56b93d9ead",
                cloudnaryPublicId: ""
            }
        ]
    },

    {
        id: "8971f3b9-d752-4faf-bf18-5a0af44065cf",
        localityInfo: "Rua das Rosas, 300\nBela Vista\n99887-123 Oliveira / MG",
        immobileType: "HABITATION",
        localLink: "https://exemplo.com/imovel3",
        status: "INANALYSIS",
        userCreationId: "a081fb4f-4e85-4a81-9458-0ead028b0b4f",
        creationDate: new Date("2023-11-10T09:15:00Z"),
        updateDate: new Date("2024-11-10T09:15:00Z"),
        postalCode: "99887-123",
        state: "MG",
        city: "Belo Horizonte",
        street: "Rua das Rosas",
        neighborhood: "Bela Vista",
        hasScripture: false,
        immobileDescription: "Condomínio fechado com área de lazer completa.",
        value: 360000,
        Images: [
            {
                id: "img-3a",
                type: "image/jpeg",
                imageUrl: "https://picsum.photos/300/200?random=7",
                size: 130000,
                name: "piscina.jpg",
                immobileId: "8971f3b9-d752-4faf-bf18-5a0af44065cf",
                cloudnaryPublicId: ""
            },
            {
                id: "img-3b",
                type: "image/jpeg",
                imageUrl: "https://picsum.photos/300/200?random=8",
                size: 140000,
                name: "salao_festas.jpg",
                immobileId: "8971f3b9-d752-4faf-bf18-5a0af44065cf",
                cloudnaryPublicId: ""
            },
            {
                id: "img-3c",
                type: "image/jpeg",
                imageUrl: "https://picsum.photos/300/200?random=9",
                size: 170000,
                name: "academia.jpg",
                immobileId: "8971f3b9-d752-4faf-bf18-5a0af44065cf",
                cloudnaryPublicId: ""
            }
        ]
    },
    {
        id: "immobile-001",
        localityInfo: "Rua das Palmeiras, 125\nCentro\n12345-678 São Paulo / SP",
        immobileType: "HABITATION",
        localLink: "https://exemplo.com/imovel1",
        status: "ACTIVE",
        userCreationId: "f8f0344d-324b-4c1c-9158-5a91c1a1c2d3",
        creationDate: new Date("2024-06-01T10:00:00Z"),
        updateDate: new Date("2025-06-01T10:00:00Z"),
        postalCode: "12345-678",
        state: "SP",
        city: "São Paulo",
        street: "Rua das Palmeiras",
        neighborhood: "Centro",
        hasScripture: true,
        immobileDescription: "Casa aconchegante com quintal amplo.",
        value: 250000,
        Images: [
            {
                id: "img-001a",
                type: "image/jpeg",
                imageUrl: "https://picsum.photos/300/200?random=1",
                size: 150000,
                name: "fachada.jpg",
                immobileId: "immobile-001",
                cloudnaryPublicId: ""
            },
            {
                id: "img-001b",
                type: "image/jpeg",
                imageUrl: "https://picsum.photos/300/200?random=2",
                size: 180000,
                name: "sala.jpg",
                immobileId: "immobile-001",
                cloudnaryPublicId: ""
            },
            {
                id: "img-001c",
                type: "image/jpeg",
                imageUrl: "https://picsum.photos/300/200?random=3",
                size: 160000,
                name: "quarto.jpg",
                immobileId: "immobile-001",
                cloudnaryPublicId: ""
            }
        ]
    },
    {
        id: "immobile-002",
        localityInfo: "Rua das Palmeiras, 126\nCentro\n12345-679 São Paulo / SP",
        immobileType: "HABITATION",
        localLink: "https://exemplo.com/imovel2",
        status: "ACTIVE",
        userCreationId: "f8f0344d-324b-4c1c-9158-5a91c1a1c2d3",
        creationDate: new Date("2024-06-02T10:00:00Z"),
        updateDate: new Date("2025-06-02T10:00:00Z"),
        postalCode: "12345-679",
        state: "SP",
        city: "São Paulo",
        street: "Rua das Palmeiras",
        neighborhood: "Centro",
        hasScripture: false,
        immobileDescription: "Casa aconchegante com quintal amplo.",
        value: 255000,
        Images: [
            {
                id: "img-002a",
                type: "image/jpeg",
                imageUrl: "https://picsum.photos/300/200?random=4",
                size: 150000,
                name: "fachada.jpg",
                immobileId: "immobile-002",
                cloudnaryPublicId: ""
            },
            {
                id: "img-002b",
                type: "image/jpeg",
                imageUrl: "https://picsum.photos/300/200?random=5",
                size: 180000,
                name: "sala.jpg",
                immobileId: "immobile-002",
                cloudnaryPublicId: ""
            },
            {
                id: "img-002c",
                type: "image/jpeg",
                imageUrl: "https://picsum.photos/300/200?random=6",
                size: 160000,
                name: "quarto.jpg",
                immobileId: "immobile-002",
                cloudnaryPublicId: ""
            }
        ]
    },
    {
        id: "immobile-003",
        localityInfo: "Rua das Palmeiras, 127\nCentro\n12345-680 São Paulo / SP",
        immobileType: "HABITATION",
        localLink: "https://exemplo.com/imovel3",
        status: "ACTIVE",
        userCreationId: "f8f0344d-324b-4c1c-9158-5a91c1a1c2d3",
        creationDate: new Date("2024-06-03T10:00:00Z"),
        updateDate: new Date("2025-06-03T10:00:00Z"),
        postalCode: "12345-680",
        state: "SP",
        city: "São Paulo",
        street: "Rua das Palmeiras",
        neighborhood: "Centro",
        hasScripture: true,
        immobileDescription: "Casa aconchegante com quintal amplo.",
        value: 260000,
        Images: [
            {
                id: "img-003a",
                type: "image/jpeg",
                imageUrl: "https://picsum.photos/300/200?random=7",
                size: 150000,
                name: "fachada.jpg",
                immobileId: "immobile-003",
                cloudnaryPublicId: ""
            },
            {
                id: "img-003b",
                type: "image/jpeg",
                imageUrl: "https://picsum.photos/300/200?random=8",
                size: 180000,
                name: "sala.jpg",
                immobileId: "immobile-003",
                cloudnaryPublicId: ""
            },
            {
                id: "img-003c",
                type: "image/jpeg",
                imageUrl: "https://picsum.photos/300/200?random=9",
                size: 160000,
                name: "quarto.jpg",
                immobileId: "immobile-003",
                cloudnaryPublicId: ""
            }
        ]
    },
    {
        id: "immobile-005",
        localityInfo: "Rua das Palmeiras, 130\nCentro\n12345-683 São Paulo / SP",
        immobileType: "HABITATION",
        localLink: "https://exemplo.com/imovel5",
        status: "ACTIVE",
        userCreationId: "f8f0344d-324b-4c1c-9158-5a91c1a1c2d3",
        creationDate: new Date("2024-06-05T10:00:00Z"),
        updateDate: new Date("2025-06-05T10:00:00Z"),
        postalCode: "12345-683",
        state: "SP",
        city: "São Paulo",
        street: "Rua das Palmeiras",
        neighborhood: "Centro",
        hasScripture: false,
        immobileDescription: "Casa aconchegante com quintal amplo.",
        value: 275000,
        Images: [
            {
                id: "img-005a",
                type: "image/jpeg",
                imageUrl: "https://picsum.photos/300/200?random=16",
                size: 150000,
                name: "fachada.jpg",
                immobileId: "immobile-005",
                cloudnaryPublicId: "",
            },
            {
                id: "img-005b",
                type: "image/jpeg",
                imageUrl: "https://picsum.photos/300/200?random=17",
                size: 180000,
                name: "sala.jpg",
                immobileId: "immobile-005",
                cloudnaryPublicId: "",
            },
            {
                id: "img-005c",
                type: "image/jpeg",
                imageUrl: "https://picsum.photos/300/200?random=18",
                size: 160000,
                name: "quarto.jpg",
                immobileId: "immobile-005",
                cloudnaryPublicId: "",
            },
        ],
    },
    {
        id: "immobile-006",
        localityInfo: "Rua das Palmeiras, 131\nCentro\n12345-684 São Paulo / SP",
        immobileType: "HABITATION",
        localLink: "https://exemplo.com/imovel6",
        status: "ACTIVE",
        userCreationId: "f8f0344d-324b-4c1c-9158-5a91c1a1c2d3",
        creationDate: new Date("2024-06-06T10:00:00Z"),
        updateDate: new Date("2025-06-06T10:00:00Z"),
        postalCode: "12345-684",
        state: "SP",
        city: "São Paulo",
        street: "Rua das Palmeiras",
        neighborhood: "Centro",
        hasScripture: true,
        immobileDescription: "Casa aconchegante com quintal amplo.",
        value: 280000,
        Images: [
            {
                id: "img-006a",
                type: "image/jpeg",
                imageUrl: "https://picsum.photos/300/200?random=19",
                size: 150000,
                name: "fachada.jpg",
                immobileId: "immobile-006",
                cloudnaryPublicId: "",
            },
            {
                id: "img-006b",
                type: "image/jpeg",
                imageUrl: "https://picsum.photos/300/200?random=20",
                size: 180000,
                name: "sala.jpg",
                immobileId: "immobile-006",
                cloudnaryPublicId: "",
            },
            {
                id: "img-006c",
                type: "image/jpeg",
                imageUrl: "https://picsum.photos/300/200?random=21",
                size: 160000,
                name: "quarto.jpg",
                immobileId: "immobile-006",
                cloudnaryPublicId: "",
            },
        ],
    },
    {
        id: "immobile-007",
        localityInfo: "Rua das Palmeiras, 132\nCentro\n12345-685 São Paulo / SP",
        immobileType: "HABITATION",
        localLink: "https://exemplo.com/imovel7",
        status: "ACTIVE",
        userCreationId: "f8f0344d-324b-4c1c-9158-5a91c1a1c2d3",
        creationDate: new Date("2024-06-07T10:00:00Z"),
        updateDate: new Date("2025-06-07T10:00:00Z"),
        postalCode: "12345-685",
        state: "SP",
        city: "São Paulo",
        street: "Rua das Palmeiras",
        neighborhood: "Centro",
        hasScripture: false,
        immobileDescription: "Casa aconchegante com quintal amplo.",
        value: 285000,
        Images: [
            {
                id: "img-007a",
                type: "image/jpeg",
                imageUrl: "https://picsum.photos/300/200?random=22",
                size: 150000,
                name: "fachada.jpg",
                immobileId: "immobile-007",
                cloudnaryPublicId: "",
            },
            {
                id: "img-007b",
                type: "image/jpeg",
                imageUrl: "https://picsum.photos/300/200?random=23",
                size: 180000,
                name: "sala.jpg",
                immobileId: "immobile-007",
                cloudnaryPublicId: "",
            },
            {
                id: "img-007c",
                type: "image/jpeg",
                imageUrl: "https://picsum.photos/300/200?random=24",
                size: 160000,
                name: "quarto.jpg",
                immobileId: "immobile-007",
                cloudnaryPublicId: "",
            },
        ],
    },
    {
        id: "immobile-008",
        localityInfo: "Rua das Palmeiras, 133\nCentro\n12345-686 São Paulo / SP",
        immobileType: "HABITATION",
        localLink: "https://exemplo.com/imovel8",
        status: "ACTIVE",
        userCreationId: "f8f0344d-324b-4c1c-9158-5a91c1a1c2d3",
        creationDate: new Date("2024-06-08T10:00:00Z"),
        updateDate: new Date("2025-06-08T10:00:00Z"),
        postalCode: "12345-686",
        state: "SP",
        city: "São Paulo",
        street: "Rua das Palmeiras",
        neighborhood: "Centro",
        hasScripture: true,
        immobileDescription: "Casa aconchegante com quintal amplo.",
        value: 290000,
        Images: [
            {
                id: "img-008a",
                type: "image/jpeg",
                imageUrl: "https://picsum.photos/300/200?random=25",
                size: 150000,
                name: "fachada.jpg",
                immobileId: "immobile-008",
                cloudnaryPublicId: "",
            },
            {
                id: "img-008b",
                type: "image/jpeg",
                imageUrl: "https://picsum.photos/300/200?random=26",
                size: 180000,
                name: "sala.jpg",
                immobileId: "immobile-008",
                cloudnaryPublicId: "",
            },
            {
                id: "img-008c",
                type: "image/jpeg",
                imageUrl: "https://picsum.photos/300/200?random=27",
                size: 160000,
                name: "quarto.jpg",
                immobileId: "immobile-008",
                cloudnaryPublicId: "",
            },
        ],
    },
    {
        id: "immobile-009",
        localityInfo: "Rua das Palmeiras, 134\nCentro\n12345-687 São Paulo / SP",
        immobileType: "HABITATION",
        localLink: "https://exemplo.com/imovel9",
        status: "ACTIVE",
        userCreationId: "f8f0344d-324b-4c1c-9158-5a91c1a1c2d3",
        creationDate: new Date("2024-06-09T10:00:00Z"),
        updateDate: new Date("2025-06-09T10:00:00Z"),
        postalCode: "12345-687",
        state: "SP",
        city: "São Paulo",
        street: "Rua das Palmeiras",
        neighborhood: "Centro",
        hasScripture: false,
        immobileDescription: "Casa aconchegante com quintal amplo.",
        value: 295000,
        Images: [
            {
                id: "img-009a",
                type: "image/jpeg",
                imageUrl: "https://picsum.photos/300/200?random=28",
                size: 150000,
                name: "fachada.jpg",
                immobileId: "immobile-009",
                cloudnaryPublicId: "",
            },
            {
                id: "img-009b",
                type: "image/jpeg",
                imageUrl: "https://picsum.photos/300/200?random=29",
                size: 180000,
                name: "sala.jpg",
                immobileId: "immobile-009",
                cloudnaryPublicId: "",
            },
            {
                id: "img-009c",
                type: "image/jpeg",
                imageUrl: "https://picsum.photos/300/200?random=30",
                size: 160000,
                name: "quarto.jpg",
                immobileId: "immobile-009",
                cloudnaryPublicId: "",
            },
        ],
    },
    {
        id: "immobile-010",
        localityInfo: "Rua das Palmeiras, 135\nCentro\n12345-688 São Paulo / SP",
        immobileType: "HABITATION",
        localLink: "https://exemplo.com/imovel10",
        status: "ACTIVE",
        userCreationId: "f8f0344d-324b-4c1c-9158-5a91c1a1c2d3",
        creationDate: new Date("2024-06-10T10:00:00Z"),
        updateDate: new Date("2025-06-10T10:00:00Z"),
        postalCode: "12345-688",
        state: "SP",
        city: "São Paulo",
        street: "Rua das Palmeiras",
        neighborhood: "Centro",
        hasScripture: true,
        immobileDescription: "Casa aconchegante com quintal amplo.",
        value: 300000,
        Images: [
            {
                id: "img-010a",
                type: "image/jpeg",
                imageUrl: "https://picsum.photos/300/200?random=31",
                size: 150000,
                name: "fachada.jpg",
                immobileId: "immobile-010",
                cloudnaryPublicId: "",
            },
            {
                id: "img-010b",
                type: "image/jpeg",
                imageUrl: "https://picsum.photos/300/200?random=32",
                size: 180000,
                name: "sala.jpg",
                immobileId: "immobile-010",
                cloudnaryPublicId: "",
            },
            {
                id: "img-010c",
                type: "image/jpeg",
                imageUrl: "https://picsum.photos/300/200?random=33",
                size: 160000,
                name: "quarto.jpg",
                immobileId: "immobile-010",
                cloudnaryPublicId: "",
            },
        ],
    },
    {
        id: "immobile-011",
        localityInfo: "Rua das Palmeiras, 136\nCentro\n12345-689 São Paulo / SP",
        immobileType: "HABITATION",
        localLink: "https://exemplo.com/imovel11",
        status: "ACTIVE",
        userCreationId: "f8f0344d-324b-4c1c-9158-5a91c1a1c2d3",
        creationDate: new Date("2024-06-11T10:00:00Z"),
        updateDate: new Date("2025-06-11T10:00:00Z"),
        postalCode: "12345-689",
        state: "SP",
        city: "São Paulo",
        street: "Rua das Palmeiras",
        neighborhood: "Centro",
        hasScripture: false,
        immobileDescription: "Casa aconchegante com quintal amplo.",
        value: 305000,
        Images: [
            {
                id: "img-011a",
                type: "image/jpeg",
                imageUrl: "https://picsum.photos/300/200?random=34",
                size: 150000,
                name: "fachada.jpg",
                immobileId: "immobile-011",
                cloudnaryPublicId: "",
            },
            {
                id: "img-011b",
                type: "image/jpeg",
                imageUrl: "https://picsum.photos/300/200?random=35",
                size: 180000,
                name: "sala.jpg",
                immobileId: "immobile-011",
                cloudnaryPublicId: "",
            },
            {
                id: "img-011c",
                type: "image/jpeg",
                imageUrl: "https://picsum.photos/300/200?random=36",
                size: 160000,
                name: "quarto.jpg",
                immobileId: "immobile-011",
                cloudnaryPublicId: "",
            },
        ],
    },
    {
        id: "immobile-012",
        localityInfo: "Rua das Palmeiras, 137\nCentro\n12345-690 São Paulo / SP",
        immobileType: "HABITATION",
        localLink: "https://exemplo.com/imovel12",
        status: "ACTIVE",
        userCreationId: "f8f0344d-324b-4c1c-9158-5a91c1a1c2d3",
        creationDate: new Date("2024-06-12T10:00:00Z"),
        updateDate: new Date("2025-06-12T10:00:00Z"),
        postalCode: "12345-690",
        state: "SP",
        city: "São Paulo",
        street: "Rua das Palmeiras",
        neighborhood: "Centro",
        hasScripture: true,
        immobileDescription: "Casa aconchegante com quintal amplo.",
        value: 310000,
        Images: [
            {
                id: "img-012a",
                type: "image/jpeg",
                imageUrl: "https://picsum.photos/300/200?random=37",
                size: 150000,
                name: "fachada.jpg",
                immobileId: "immobile-012",
                cloudnaryPublicId: "",
            },
            {
                id: "img-012b",
                type: "image/jpeg",
                imageUrl: "https://picsum.photos/300/200?random=38",
                size: 180000,
                name: "sala.jpg",
                immobileId: "immobile-012",
                cloudnaryPublicId: "",
            },
            {
                id: "img-012c",
                type: "image/jpeg",
                imageUrl: "https://picsum.photos/300/200?random=39",
                size: 160000,
                name: "quarto.jpg",
                immobileId: "immobile-012",
                cloudnaryPublicId: "",
            },
        ],
    },
    {
        id: "immobile-013",
        localityInfo: "Rua das Palmeiras, 138\nCentro\n12345-691 São Paulo / SP",
        immobileType: "HABITATION",
        localLink: "https://exemplo.com/imovel13",
        status: "ACTIVE",
        userCreationId: "f8f0344d-324b-4c1c-9158-5a91c1a1c2d3",
        creationDate: new Date("2024-06-13T10:00:00Z"),
        updateDate: new Date("2025-06-13T10:00:00Z"),
        postalCode: "12345-691",
        state: "SP",
        city: "São Paulo",
        street: "Rua das Palmeiras",
        neighborhood: "Centro",
        hasScripture: false,
        immobileDescription: "Casa aconchegante com quintal amplo.",
        value: 315000,
        Images: [
            {
                id: "img-013a",
                type: "image/jpeg",
                imageUrl: "https://picsum.photos/300/200?random=40",
                size: 150000,
                name: "fachada.jpg",
                immobileId: "immobile-013",
                cloudnaryPublicId: "",
            },
            {
                id: "img-013b",
                type: "image/jpeg",
                imageUrl: "https://picsum.photos/300/200?random=41",
                size: 180000,
                name: "sala.jpg",
                immobileId: "immobile-013",
                cloudnaryPublicId: "",
            },
            {
                id: "img-013c",
                type: "image/jpeg",
                imageUrl: "https://picsum.photos/300/200?random=42",
                size: 160000,
                name: "quarto.jpg",
                immobileId: "immobile-013",
                cloudnaryPublicId: "",
            },
        ],
    },
    {
        id: "immobile-014",
        localityInfo: "Rua das Palmeiras, 139\nCentro\n12345-692 São Paulo / SP",
        immobileType: "HABITATION",
        localLink: "https://exemplo.com/imovel14",
        status: "ACTIVE",
        userCreationId: "f8f0344d-324b-4c1c-9158-5a91c1a1c2d3",
        creationDate: new Date("2024-06-14T10:00:00Z"),
        updateDate: new Date("2025-06-14T10:00:00Z"),
        postalCode: "12345-692",
        state: "SP",
        city: "São Paulo",
        street: "Rua das Palmeiras",
        neighborhood: "Centro",
        hasScripture: true,
        immobileDescription: "Casa aconchegante com quintal amplo.",
        value: 320000,
        Images: [
            {
                id: "img-014a",
                type: "image/jpeg",
                imageUrl: "https://picsum.photos/300/200?random=43",
                size: 150000,
                name: "fachada.jpg",
                immobileId: "immobile-014",
                cloudnaryPublicId: "",
            },
            {
                id: "img-014b",
                type: "image/jpeg",
                imageUrl: "https://picsum.photos/300/200?random=44",
                size: 180000,
                name: "sala.jpg",
                immobileId: "immobile-014",
                cloudnaryPublicId: "",
            },
            {
                id: "img-014c",
                type: "image/jpeg",
                imageUrl: "https://picsum.photos/300/200?random=45",
                size: 160000,
                name: "quarto.jpg",
                immobileId: "immobile-014",
                cloudnaryPublicId: "",
            },
        ],
    },
    {
        id: "immobile-015",
        localityInfo: "Rua das Palmeiras, 140\nCentro\n12345-693 São Paulo / SP",
        immobileType: "HABITATION",
        localLink: "https://exemplo.com/imovel15",
        status: "ACTIVE",
        userCreationId: "f8f0344d-324b-4c1c-9158-5a91c1a1c2d3",
        creationDate: new Date("2024-06-15T10:00:00Z"),
        updateDate: new Date("2025-06-15T10:00:00Z"),
        postalCode: "12345-693",
        state: "SP",
        city: "São Paulo",
        street: "Rua das Palmeiras",
        neighborhood: "Centro",
        hasScripture: false,
        immobileDescription: "Casa aconchegante com quintal amplo.",
        value: 325000,
        Images: [
            {
                id: "img-015a",
                type: "image/jpeg",
                imageUrl: "https://picsum.photos/300/200?random=46",
                size: 150000,
                name: "fachada.jpg",
                immobileId: "immobile-015",
                cloudnaryPublicId: "",
            },
            {
                id: "img-015b",
                type: "image/jpeg",
                imageUrl: "https://picsum.photos/300/200?random=47",
                size: 180000,
                name: "sala.jpg",
                immobileId: "immobile-015",
                cloudnaryPublicId: "",
            },
            {
                id: "img-015c",
                type: "image/jpeg",
                imageUrl: "https://picsum.photos/300/200?random=48",
                size: 160000,
                name: "quarto.jpg",
                immobileId: "immobile-015",
                cloudnaryPublicId: "",
            },
        ],
    },
    {
        id: "immobile-016",
        localityInfo: "Rua das Palmeiras, 141\nCentro\n12345-694 São Paulo / SP",
        immobileType: "HABITATION",
        localLink: "https://exemplo.com/imovel16",
        status: "ACTIVE",
        userCreationId: "f8f0344d-324b-4c1c-9158-5a91c1a1c2d3",
        creationDate: new Date("2024-06-16T10:00:00Z"),
        updateDate: new Date("2025-06-16T10:00:00Z"),
        postalCode: "12345-694",
        state: "SP",
        city: "São Paulo",
        street: "Rua das Palmeiras",
        neighborhood: "Centro",
        hasScripture: true,
        immobileDescription: "Casa aconchegante com quintal amplo.",
        value: 330000,
        Images: [
            {
                id: "img-016a",
                type: "image/jpeg",
                imageUrl: "https://picsum.photos/300/200?random=49",
                size: 150000,
                name: "fachada.jpg",
                immobileId: "immobile-016",
                cloudnaryPublicId: "",
            },
            {
                id: "img-016b",
                type: "image/jpeg",
                imageUrl: "https://picsum.photos/300/200?random=50",
                size: 180000,
                name: "sala.jpg",
                immobileId: "immobile-016",
                cloudnaryPublicId: "",
            },
            {
                id: "img-016c",
                type: "image/jpeg",
                imageUrl: "https://picsum.photos/300/200?random=51",
                size: 160000,
                name: "quarto.jpg",
                immobileId: "immobile-016",
                cloudnaryPublicId: "",
            },
        ],
    },
    {
        id: "immobile-017",
        localityInfo: "Rua das Palmeiras, 142\nCentro\n12345-695 São Paulo / SP",
        immobileType: "HABITATION",
        localLink: "https://exemplo.com/imovel17",
        status: "ACTIVE",
        userCreationId: "f8f0344d-324b-4c1c-9158-5a91c1a1c2d3",
        creationDate: new Date("2024-06-17T10:00:00Z"),
        updateDate: new Date("2025-06-17T10:00:00Z"),
        postalCode: "12345-695",
        state: "SP",
        city: "São Paulo",
        street: "Rua das Palmeiras",
        neighborhood: "Centro",
        hasScripture: false,
        immobileDescription: "Casa aconchegante com quintal amplo.",
        value: 335000,
        Images: [
            {
                id: "img-017a",
                type: "image/jpeg",
                imageUrl: "https://picsum.photos/300/200?random=52",
                size: 150000,
                name: "fachada.jpg",
                immobileId: "immobile-017",
                cloudnaryPublicId: "",
            },
            {
                id: "img-017b",
                type: "image/jpeg",
                imageUrl: "https://picsum.photos/300/200?random=53",
                size: 180000,
                name: "sala.jpg",
                immobileId: "immobile-017",
                cloudnaryPublicId: "",
            },
            {
                id: "img-017c",
                type: "image/jpeg",
                imageUrl: "https://picsum.photos/300/200?random=54",
                size: 160000,
                name: "quarto.jpg",
                immobileId: "immobile-017",
                cloudnaryPublicId: "",
            },
        ],
    },
    {
        id: "immobile-018",
        localityInfo: "Rua das Palmeiras, 143\nCentro\n12345-696 São Paulo / SP",
        immobileType: "HABITATION",
        localLink: "https://exemplo.com/imovel18",
        status: "ACTIVE",
        userCreationId: "f8f0344d-324b-4c1c-9158-5a91c1a1c2d3",
        creationDate: new Date("2024-06-18T10:00:00Z"),
        updateDate: new Date("2025-06-18T10:00:00Z"),
        postalCode: "12345-696",
        state: "SP",
        city: "São Paulo",
        street: "Rua das Palmeiras",
        neighborhood: "Centro",
        hasScripture: true,
        immobileDescription: "Casa aconchegante com quintal amplo.",
        value: 340000,
        Images: [
            {
                id: "img-018a",
                type: "image/jpeg",
                imageUrl: "https://picsum.photos/300/200?random=55",
                size: 150000,
                name: "fachada.jpg",
                immobileId: "immobile-018",
                cloudnaryPublicId: "",
            },
            {
                id: "img-018b",
                type: "image/jpeg",
                imageUrl: "https://picsum.photos/300/200?random=56",
                size: 180000,
                name: "sala.jpg",
                immobileId: "immobile-018",
                cloudnaryPublicId: "",
            },
            {
                id: "img-018c",
                type: "image/jpeg",
                imageUrl: "https://picsum.photos/300/200?random=57",
                size: 160000,
                name: "quarto.jpg",
                immobileId: "immobile-018",
                cloudnaryPublicId: "",
            },
        ],
    },
    {
        id: "immobile-019",
        localityInfo: "Rua das Palmeiras, 144\nCentro\n12345-697 São Paulo / SP",
        immobileType: "HABITATION",
        localLink: "https://exemplo.com/imovel19",
        status: "ACTIVE",
        userCreationId: "f8f0344d-324b-4c1c-9158-5a91c1a1c2d3",
        creationDate: new Date("2024-06-19T10:00:00Z"),
        updateDate: new Date("2025-06-19T10:00:00Z"),
        postalCode: "12345-697",
        state: "SP",
        city: "São Paulo",
        street: "Rua das Palmeiras",
        neighborhood: "Centro",
        hasScripture: false,
        immobileDescription: "Casa aconchegante com quintal amplo.",
        value: 345000,
        Images: [
            {
                id: "img-019a",
                type: "image/jpeg",
                imageUrl: "https://picsum.photos/300/200?random=58",
                size: 150000,
                name: "fachada.jpg",
                immobileId: "immobile-019",
                cloudnaryPublicId: "",
            },
            {
                id: "img-019b",
                type: "image/jpeg",
                imageUrl: "https://picsum.photos/300/200?random=59",
                size: 180000,
                name: "sala.jpg",
                immobileId: "immobile-019",
                cloudnaryPublicId: "",
            },
            {
                id: "img-019c",
                type: "image/jpeg",
                imageUrl: "https://picsum.photos/300/200?random=60",
                size: 160000,
                name: "quarto.jpg",
                immobileId: "immobile-019",
                cloudnaryPublicId: "",
            },
        ],
    },
    {
        id: "immobile-020",
        localityInfo: "Rua das Palmeiras, 145\nCentro\n12345-698 São Paulo / SP",
        immobileType: "HABITATION",
        localLink: "https://exemplo.com/imovel20",
        status: "ACTIVE",
        userCreationId: "f8f0344d-324b-4c1c-9158-5a91c1a1c2d3",
        creationDate: new Date("2024-06-20T10:00:00Z"),
        updateDate: new Date("2025-06-20T10:00:00Z"),
        postalCode: "12345-698",
        state: "SP",
        city: "São Paulo",
        street: "Rua das Palmeiras",
        neighborhood: "Centro",
        hasScripture: true,
        immobileDescription: "Casa aconchegante com quintal amplo.",
        value: 350000,
        Images: [
            {
                id: "img-020a",
                type: "image/jpeg",
                imageUrl: "https://picsum.photos/300/200?random=61",
                size: 150000,
                name: "fachada.jpg",
                immobileId: "immobile-020",
                cloudnaryPublicId: "",
            },
            {
                id: "img-020b",
                type: "image/jpeg",
                imageUrl: "https://picsum.photos/300/200?random=62",
                size: 180000,
                name: "sala.jpg",
                immobileId: "immobile-020",
                cloudnaryPublicId: "",
            },
            {
                id: "img-020c",
                type: "image/jpeg",
                imageUrl: "https://picsum.photos/300/200?random=63",
                size: 160000,
                name: "quarto.jpg",
                immobileId: "immobile-020",
                cloudnaryPublicId: "",
            },
        ],
    },
    {
        id: "immobile-021",
        localityInfo: "Rua das Palmeiras, 146\nCentro\n12345-699 São Paulo / SP",
        immobileType: "HABITATION",
        localLink: "https://exemplo.com/imovel21",
        status: "ACTIVE",
        userCreationId: "f8f0344d-324b-4c1c-9158-5a91c1a1c2d3",
        creationDate: new Date("2024-06-21T10:00:00Z"),
        updateDate: new Date("2025-06-21T10:00:00Z"),
        postalCode: "12345-699",
        state: "SP",
        city: "São Paulo",
        street: "Rua das Palmeiras",
        neighborhood: "Centro",
        hasScripture: false,
        immobileDescription: "Casa aconchegante com quintal amplo.",
        value: 355000,
        Images: [
            {
                id: "img-021a",
                type: "image/jpeg",
                imageUrl: "https://picsum.photos/300/200?random=64",
                size: 150000,
                name: "fachada.jpg",
                immobileId: "immobile-021",
                cloudnaryPublicId: "",
            },
            {
                id: "img-021b",
                type: "image/jpeg",
                imageUrl: "https://picsum.photos/300/200?random=65",
                size: 180000,
                name: "sala.jpg",
                immobileId: "immobile-021",
                cloudnaryPublicId: "",
            },
            {
                id: "img-021c",
                type: "image/jpeg",
                imageUrl: "https://picsum.photos/300/200?random=66",
                size: 160000,
                name: "quarto.jpg",
                immobileId: "immobile-021",
                cloudnaryPublicId: "",
            },
        ],
    },
    {
        id: "immobile-022",
        localityInfo: "Rua das Palmeiras, 147\nCentro\n12345-700 São Paulo / SP",
        immobileType: "HABITATION",
        localLink: "https://exemplo.com/imovel22",
        status: "ACTIVE",
        userCreationId: "f8f0344d-324b-4c1c-9158-5a91c1a1c2d3",
        creationDate: new Date("2024-06-22T10:00:00Z"),
        updateDate: new Date("2025-06-22T10:00:00Z"),
        postalCode: "12345-700",
        state: "SP",
        city: "São Paulo",
        street: "Rua das Palmeiras",
        neighborhood: "Centro",
        hasScripture: true,
        immobileDescription: "Casa aconchegante com quintal amplo.",
        value: 360000,
        Images: [
            {
                id: "img-022a",
                type: "image/jpeg",
                imageUrl: "https://picsum.photos/300/200?random=67",
                size: 150000,
                name: "fachada.jpg",
                immobileId: "immobile-022",
                cloudnaryPublicId: "",
            },
            {
                id: "img-022b",
                type: "image/jpeg",
                imageUrl: "https://picsum.photos/300/200?random=68",
                size: 180000,
                name: "sala.jpg",
                immobileId: "immobile-022",
                cloudnaryPublicId: "",
            },
            {
                id: "img-022c",
                type: "image/jpeg",
                imageUrl: "https://picsum.photos/300/200?random=69",
                size: 160000,
                name: "quarto.jpg",
                immobileId: "immobile-022",
                cloudnaryPublicId: "",
            },
        ],
    },
    {
        id: "immobile-023",
        localityInfo: "Rua das Palmeiras, 148\nCentro\n12345-701 São Paulo / SP",
        immobileType: "HABITATION",
        localLink: "https://exemplo.com/imovel23",
        status: "ACTIVE",
        userCreationId: "f8f0344d-324b-4c1c-9158-5a91c1a1c2d3",
        creationDate: new Date("2024-06-23T10:00:00Z"),
        updateDate: new Date("2025-06-23T10:00:00Z"),
        postalCode: "12345-701",
        state: "SP",
        city: "São Paulo",
        street: "Rua das Palmeiras",
        neighborhood: "Centro",
        hasScripture: false,
        immobileDescription: "Casa aconchegante com quintal amplo.",
        value: 365000,
        Images: [
            {
                id: "img-023a",
                type: "image/jpeg",
                imageUrl: "https://picsum.photos/300/200?random=70",
                size: 150000,
                name: "fachada.jpg",
                immobileId: "immobile-023",
                cloudnaryPublicId: "",
            },
            {
                id: "img-023b",
                type: "image/jpeg",
                imageUrl: "https://picsum.photos/300/200?random=71",
                size: 180000,
                name: "sala.jpg",
                immobileId: "immobile-023",
                cloudnaryPublicId: "",
            },
            {
                id: "img-023c",
                type: "image/jpeg",
                imageUrl: "https://picsum.photos/300/200?random=72",
                size: 160000,
                name: "quarto.jpg",
                immobileId: "immobile-023",
                cloudnaryPublicId: "",
            },
        ],
    },
    {
        id: "immobile-024",
        localityInfo: "Rua das Palmeiras, 149\nCentro\n12345-702 São Paulo / SP",
        immobileType: "HABITATION",
        localLink: "https://exemplo.com/imovel24",
        status: "ACTIVE",
        userCreationId: "f8f0344d-324b-4c1c-9158-5a91c1a1c2d3",
        creationDate: new Date("2024-06-24T10:00:00Z"),
        updateDate: new Date("2025-06-24T10:00:00Z"),
        postalCode: "12345-702",
        state: "SP",
        city: "São Paulo",
        street: "Rua das Palmeiras",
        neighborhood: "Centro",
        hasScripture: true,
        immobileDescription: "Casa aconchegante com quintal amplo.",
        value: 370000,
        Images: [
            {
                id: "img-024a",
                type: "image/jpeg",
                imageUrl: "https://picsum.photos/300/200?random=73",
                size: 150000,
                name: "fachada.jpg",
                immobileId: "immobile-024",
                cloudnaryPublicId: "",
            },
            {
                id: "img-024b",
                type: "image/jpeg",
                imageUrl: "https://picsum.photos/300/200?random=74",
                size: 180000,
                name: "sala.jpg",
                immobileId: "immobile-024",
                cloudnaryPublicId: "",
            },
            {
                id: "img-024c",
                type: "image/jpeg",
                imageUrl: "https://picsum.photos/300/200?random=75",
                size: 160000,
                name: "quarto.jpg",
                immobileId: "immobile-024",
                cloudnaryPublicId: "",
            },
        ],
    },
    {
        id: "immobile-025",
        localityInfo: "Rua das Palmeiras, 150\nCentro\n12345-703 São Paulo / SP",
        immobileType: "HABITATION",
        localLink: "https://exemplo.com/imovel25",
        status: "ACTIVE",
        userCreationId: "f8f0344d-324b-4c1c-9158-5a91c1a1c2d3",
        creationDate: new Date("2024-06-25T10:00:00Z"),
        updateDate: new Date("2025-06-25T10:00:00Z"),
        postalCode: "12345-703",
        state: "SP",
        city: "São Paulo",
        street: "Rua das Palmeiras",
        neighborhood: "Centro",
        hasScripture: false,
        immobileDescription: "Casa aconchegante com quintal amplo.",
        value: 375000,
        Images: [
            {
                id: "img-025a",
                type: "image/jpeg",
                imageUrl: "https://picsum.photos/300/200?random=76",
                size: 150000,
                name: "fachada.jpg",
                immobileId: "immobile-025",
                cloudnaryPublicId: "",
            },
            {
                id: "img-025b",
                type: "image/jpeg",
                imageUrl: "https://picsum.photos/300/200?random=77",
                size: 180000,
                name: "sala.jpg",
                immobileId: "immobile-025",
                cloudnaryPublicId: "",
            },
            {
                id: "img-025c",
                type: "image/jpeg",
                imageUrl: "https://picsum.photos/300/200?random=78",
                size: 160000,
                name: "quarto.jpg",
                immobileId: "immobile-025",
                cloudnaryPublicId: "",
            },
        ],
    },
    {
        id: "immobile-026",
        localityInfo: "Rua das Palmeiras, 151\nCentro\n12345-704 São Paulo / SP",
        immobileType: "HABITATION",
        localLink: "https://exemplo.com/imovel26",
        status: "ACTIVE",
        userCreationId: "f8f0344d-324b-4c1c-9158-5a91c1a1c2d3",
        creationDate: new Date("2024-06-26T10:00:00Z"),
        updateDate: new Date("2025-06-26T10:00:00Z"),
        postalCode: "12345-704",
        state: "SP",
        city: "São Paulo",
        street: "Rua das Palmeiras",
        neighborhood: "Centro",
        hasScripture: true,
        immobileDescription: "Casa aconchegante com quintal amplo.",
        value: 380000,
        Images: [
            {
                id: "img-026a",
                type: "image/jpeg",
                imageUrl: "https://picsum.photos/300/200?random=79",
                size: 150000,
                name: "fachada.jpg",
                immobileId: "immobile-026",
                cloudnaryPublicId: "",
            },
            {
                id: "img-026b",
                type: "image/jpeg",
                imageUrl: "https://picsum.photos/300/200?random=80",
                size: 180000,
                name: "sala.jpg",
                immobileId: "immobile-026",
                cloudnaryPublicId: "",
            },
            {
                id: "img-026c",
                type: "image/jpeg",
                imageUrl: "https://picsum.photos/300/200?random=81",
                size: 160000,
                name: "quarto.jpg",
                immobileId: "immobile-026",
                cloudnaryPublicId: "",
            },
        ],
    },
    {
        id: "immobile-027",
        localityInfo: "Rua das Palmeiras, 152\nCentro\n12345-705 São Paulo / SP",
        immobileType: "HABITATION",
        localLink: "https://exemplo.com/imovel27",
        status: "ACTIVE",
        userCreationId: "f8f0344d-324b-4c1c-9158-5a91c1a1c2d3",
        creationDate: new Date("2024-06-27T10:00:00Z"),
        updateDate: new Date("2025-06-27T10:00:00Z"),
        postalCode: "12345-705",
        state: "SP",
        city: "São Paulo",
        street: "Rua das Palmeiras",
        neighborhood: "Centro",
        hasScripture: false,
        immobileDescription: "Casa aconchegante com quintal amplo.",
        value: 385000,
        Images: [
            {
                id: "img-027a",
                type: "image/jpeg",
                imageUrl: "https://picsum.photos/300/200?random=82",
                size: 150000,
                name: "fachada.jpg",
                immobileId: "immobile-027",
                cloudnaryPublicId: "",
            },
            {
                id: "img-027b",
                type: "image/jpeg",
                imageUrl: "https://picsum.photos/300/200?random=83",
                size: 180000,
                name: "sala.jpg",
                immobileId: "immobile-027",
                cloudnaryPublicId: "",
            },
            {
                id: "img-027c",
                type: "image/jpeg",
                imageUrl: "https://picsum.photos/300/200?random=84",
                size: 160000,
                name: "quarto.jpg",
                immobileId: "immobile-027",
                cloudnaryPublicId: "",
            },
        ],
    },
    {
        id: "immobile-028",
        localityInfo: "Rua das Palmeiras, 153\nCentro\n12345-706 São Paulo / SP",
        immobileType: "HABITATION",
        localLink: "https://exemplo.com/imovel28",
        status: "ACTIVE",
        userCreationId: "f8f0344d-324b-4c1c-9158-5a91c1a1c2d3",
        creationDate: new Date("2024-06-28T10:00:00Z"),
        updateDate: new Date("2025-06-28T10:00:00Z"),
        postalCode: "12345-706",
        state: "SP",
        city: "São Paulo",
        street: "Rua das Palmeiras",
        neighborhood: "Centro",
        hasScripture: true,
        immobileDescription: "Casa aconchegante com quintal amplo.",
        value: 390000,
        Images: [
            {
                id: "img-028a",
                type: "image/jpeg",
                imageUrl: "https://picsum.photos/300/200?random=85",
                size: 150000,
                name: "fachada.jpg",
                immobileId: "immobile-028",
                cloudnaryPublicId: "",
            },
            {
                id: "img-028b",
                type: "image/jpeg",
                imageUrl: "https://picsum.photos/300/200?random=86",
                size: 180000,
                name: "sala.jpg",
                immobileId: "immobile-028",
                cloudnaryPublicId: "",
            },
            {
                id: "img-028c",
                type: "image/jpeg",
                imageUrl: "https://picsum.photos/300/200?random=87",
                size: 160000,
                name: "quarto.jpg",
                immobileId: "immobile-028",
                cloudnaryPublicId: "",
            },
        ],
    },
    {
        id: "immobile-029",
        localityInfo: "Rua das Palmeiras, 154\nCentro\n12345-707 São Paulo / SP",
        immobileType: "HABITATION",
        localLink: "https://exemplo.com/imovel29",
        status: "ACTIVE",
        userCreationId: "f8f0344d-324b-4c1c-9158-5a91c1a1c2d3",
        creationDate: new Date("2024-06-29T10:00:00Z"),
        updateDate: new Date("2025-06-29T10:00:00Z"),
        postalCode: "12345-707",
        state: "SP",
        city: "São Paulo",
        street: "Rua das Palmeiras",
        neighborhood: "Centro",
        hasScripture: false,
        immobileDescription: "Casa aconchegante com quintal amplo.",
        value: 395000,
        Images: [
            {
                id: "img-029a",
                type: "image/jpeg",
                imageUrl: "https://picsum.photos/300/200?random=88",
                size: 150000,
                name: "fachada.jpg",
                immobileId: "immobile-029",
                cloudnaryPublicId: "",
            },
            {
                id: "img-029b",
                type: "image/jpeg",
                imageUrl: "https://picsum.photos/300/200?random=89",
                size: 180000,
                name: "sala.jpg",
                immobileId: "immobile-029",
                cloudnaryPublicId: "",
            },
            {
                id: "img-029c",
                type: "image/jpeg",
                imageUrl: "https://picsum.photos/300/200?random=90",
                size: 160000,
                name: "quarto.jpg",
                immobileId: "immobile-029",
                cloudnaryPublicId: "",
            },
        ],
    },
    {
        id: "immobile-030",
        localityInfo: "Rua das Palmeiras, 155\nCentro\n12345-708 São Paulo / SP",
        immobileType: "HABITATION",
        localLink: "https://exemplo.com/imovel30",
        status: "ACTIVE",
        userCreationId: "f8f0344d-324b-4c1c-9158-5a91c1a1c2d3",
        creationDate: new Date("2024-06-30T10:00:00Z"),
        updateDate: new Date("2025-06-30T10:00:00Z"),
        postalCode: "12345-708",
        state: "SP",
        city: "São Paulo",
        street: "Rua das Palmeiras",
        neighborhood: "Centro",
        hasScripture: true,
        immobileDescription: "Casa aconchegante com quintal amplo.",
        value: 400000,
        Images: [
            {
                id: "img-030a",
                type: "image/jpeg",
                imageUrl: "https://picsum.photos/300/200?random=91",
                size: 150000,
                name: "fachada.jpg",
                immobileId: "immobile-030",
                cloudnaryPublicId: "",
            },
            {
                id: "img-030b",
                type: "image/jpeg",
                imageUrl: "https://picsum.photos/300/200?random=92",
                size: 180000,
                name: "sala.jpg",
                immobileId: "immobile-030",
                cloudnaryPublicId: "",
            },
            {
                id: "img-030c",
                type: "image/jpeg",
                imageUrl: "https://picsum.photos/300/200?random=93",
                size: 160000,
                name: "quarto.jpg",
                immobileId: "immobile-030",
                cloudnaryPublicId: "",
            },
        ],
    },

];